### ISSUE TITLE
using laraflat with one langue

### ISSUE THREAD

**Issue by webly4u** [zizohassan/laraflat#1]
Salam;
it's possible te use laraflat with just one langue 
thanks advance

**Comment by zizohassan** [comment]
yes its possible just go to this file ,
config/laravellocalization.php,
comment all language you do not need ,
and in the same file change this key to false
'useAcceptLanguageHeader' => false,
then to to this file config/app.php,
change this config key  'locale' => 'ar'  to what you need

**Comment by zizohassan** [comment]
video 
https://5dmat-web.com/video/832/
