### ISSUE TITLE
Error Exception 

### ISSUE THREAD

**Issue by ghadahedwa** [zizohassan/laraflat#10]
when add a new user without write the password
![error](https://user-images.githubusercontent.com/28937867/27707898-3e7766c2-5d17-11e7-9083-3804e706a7d4.png)

**Comment by ghadahedwa** [comment]
validation required on the password doesn't work
if I change the validation of categories from 'name.*' => 'required|max:90' to 'name' => 'required|max:90' doesn't work
what is the problem?

**Comment by thePirateAhm** [comment]
there is an error in console that say
"Error: Invalid dimensions for plot, width = null, height = null"
in the file "jquery.flot.js"

**Comment by zizohassan** [comment]
we will check ..

**Comment by zizohassan** [comment]
fixed
