### ISSUE TITLE
Error in translation view index.balde.php (Translation Control Files)

### ISSUE THREAD

**Issue by mbarky** [zizohassan/laraflat#100]
#when you click on edit (NOT Edit All Language) **LaraFlat 3.0.0** 
you will get 404 error Page not found 
Solution:
Replace 
line #NO 22 
OLD `                        <a href="/admin/translation/readFile/{{ $localeCode.'_'.end($path) }}">{{ trans('admin.Edit') }} </a>
`
with this code

`                           <a href="{{ url('admin/translation/readFile/') }}/{{$localeCode.'_'.end($path) }}">{{ trans('admin.Edit') }} </a>`

Regards 💯 👍

**Comment by zizohassan** [comment]
You can make pull request and we will accept this
