### ISSUE TITLE
Trying to get property of non-object 

### ISSUE THREAD

**Issue by Ammar777** [zizohassan/laraflat#109]
Trying to get property of non-object (View: C:\Users\One_1\Desktop\cmms\new-git-project\laraflat\app\Application\views\website\theme\bootstrap\home.blade.php)

<?php
 
function getSetting($name){
    return \App\Application\Model\Setting::where('name' , $name)->first()->body_setting;
}
Arguments
"Trying to get property of non-object (View: C:\Users\One_1\Desktop\cmms\new-git-project\laraflat\app\Application\views\website\theme\bootstrap\home.blade.php)"

**Comment by aboessa** [comment]
you forget to do db:seed
write this command in  :  php artisan db:seed

**Comment by Ammar777** [comment]
i reinstalled the project

**Comment by Ammar777** [comment]
thanks
