### ISSUE TITLE
why show file dont work?

### ISSUE THREAD

**Issue by amine8ghandi8amine** [zizohassan/laraflat#13]
ErrorException in arrays.php line 50:
array_combine(): Both parameters should have an equal number of elements
in arrays.php line 50
at HandleExceptions->handleError(2, 'array_combine(): Both parameters should have an equal number of elements', '/home/vagrant/Code/laraflat/app/Application/Helpers/arrays.php', 50, array('array' => array('name', 'created_at', 'updated_at'), 'replacement_keys' => array('UserName')))

--------------------------------------CODE-------------------------------------------------

@extends(layoutExtend())

@section('title')
    {{ adminTrans('country' , 'country') }} {{ adminTrans('home' , 'view') }}
@endsection

@section('content')
    @component(layoutForm() , ['title' => adminTrans('country' , 'country') , 'model' => 'country' , 'action' => adminTrans('home' , 'view')  ])

        <table class="table table-bordered table-responsive table-striped">
            @php
                $fields = rename_keys(
                     removeFromArray($data['fields'] , ['id']) ,
                     ['UserName']
                );
            @endphp
                 @foreach($fields as $key =>  $field)
                        <tr>
                            <th>{{ $key }}</th>
                            @php $type =  getFileType($field , $item[$field]) @endphp
                            @if($type == 'File')
                                <td> <a href="{{ url(env('UPLOAD_PATH').'/'.$item[$field]) }}">{{ $item[$field] }}</a></td>
                            @elseif($type == 'Image')
                                <td> <img src="{{ url(env('UPLOAD_PATH').'/'.$item[$field]) }}" /></td>
                            @else
                                 <td>{!!  nl2br($item[$field])  !!}</td>
                            @endif
                        </tr>
                    @endforeach
        </table>

        @include('admin.country.buttons.delete' , ['id' => $item->id])
        @include('admin.country.buttons.edit' , ['id' => $item->id])

    @endcomponent
@endsection

**Comment by zizohassan** [comment]
show file come with all columns in database so you must 
remove all not require columns in this array
       removeFromArray($data['fields'] , ['id']) ,
and put all you want to show here in this array
       ['UserName']
