### ISSUE TITLE
when project running on online server

### ISSUE THREAD

**Issue by ahmedswar68** [zizohassan/laraflat#25]
great effort but I faced a little problem when project running on an online server and I logged as admin I can't access the admin page it redirected me to default homepage.
note it working on localhost correctly.

**Comment by zizohassan** [comment]
this mean not have permission on this section you go to show
you must add permission to it

**Comment by ahmedswar68** [comment]
It working correctly on localhost with the same code and database

**Comment by zizohassan** [comment]
we can help if you give us access to see what happen

**Comment by ahmedswar68** [comment]
I solved it. the problem was in AdminMiddleware 
if(Auth::user()->group_id !== 1)    this is return false because Auth::user()->group_id is 1 but it is a string 
if you remove one of = it working correctly

**Comment by mohammed-elattar** [comment]
@ahmedswar68  please check the new issue that i created , if you have any solutions as i need to sort it out asap 
Thanks in advance

**Comment by zizohassan** [comment]
@ahmedswar68 perfect we will fix it
