### ISSUE TITLE
make:admin_model bug

### ISSUE THREAD

**Issue by scandar** [zizohassan/laraflat#26]
i updated a 5.4 project i've been working on for a while to 5.5 i changed composer.json to the new version 
the problem is when i type the command "php artisan make:admin_model" what happens is that a normal laravel model gets created inside of 'App' folder, not the expected laraflat model files

**Comment by zizohassan** [comment]
search for fire() methods on this path 
laraflat/app/Console/Commands/
and change it to handle()
in all files

**Comment by mahdi7abash** [comment]
Salam @zizohassan
first i tried make:admin_model it shows below error attached 

![admin_model error](https://user-images.githubusercontent.com/14835811/42263451-b90d750c-7f76-11e8-8774-79b64a3100e1.png)

after that i search in issues related to project i found this bug 
so i enter the file laraflat/app/Console/Commands/ 
and open MakeAdminModel.php 
i change line 21 
from  protected $name = 'laraflat:admin_model'; 
to  protected $name = 'make:admin_model';
after that i run the command again and it show

![make error](https://user-images.githubusercontent.com/14835811/42263468-c53aab1a-7f76-11e8-83ee-9a07d7214535.png)

any help please ..
