### ISSUE TITLE
how can i update bootstrap and and change the theme?

### ISSUE THREAD

**Issue by fmnmt27** [zizohassan/laraflat#29]
how can i update bootstrap and and change the theme.

**Comment by zizohassan** [comment]
about the theme
we support two theme on laraflat project you can switch between them in env file (THEME = themeone , default)

what you mean about update bootstrap

**Comment by fmnmt27** [comment]
upgrade from bootstrap3 to bootstrap4 can i use this 
npm install bootstrap@4.0.0-beta.2

**Comment by zizohassan** [comment]
yes you can  use any version of bootstrap

**Comment by fmnmt27** [comment]
When i put this npm install bootstrap@4.0.0-beta.2 in my terminal i have this error


MacBook-Air-alkhas-b-Tito:mylaraflat myuser$ npm install bootstrap@4.0.0-beta.2
-bash: npm: command not found
???

**Comment by zizohassan** [comment]
you must install nodejs
https://nodejs.org/en/

**Comment by fmnmt27** [comment]
after install node.is
npm WARN bootstrap@4.0.0-beta.2 requires a peer of jquery@1.9.1 - 3 but none was installed.
npm WARN bootstrap@4.0.0-beta.2 requires a peer of popper.js@^1.12.3 but none was installed.

**Comment by zizohassan** [comment]
install this  dependencies that require and this will work fine
