### ISSUE TITLE
migrate error

### ISSUE THREAD

**Issue by Gouda01** [zizohassan/laraflat#31]
when i make migrate it show that error :
PHP Warning:  require(C:\ionic\easysoft\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\ionic\easysoft\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\ionic\easysoft\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\ionic\easysoft\bootstrap\autoload.php on line 17

**Comment by zizohassan** [comment]
composer dumpautoload
