### ISSUE TITLE
laraflat istall on windows 7

### ISSUE THREAD

**Issue by ehabfoad** [zizohassan/laraflat#33]
@zizohassan 

C:\Users\ehab\blog\laraflat-master>php artisan serve
PHP Warning:  require(C:\Users\ehab\blog\laraflat-master\bootstrap/../vendor/aut
oload.php): failed to open stream: No such file or directory in C:\Users\ehab\bl
og\laraflat-master\bootstrap\autoload.php on line 17

Warning: require(C:\Users\ehab\blog\laraflat-master\bootstrap/../vendor/autoload
.php): failed to open stream: No such file or directory in C:\Users\ehab\blog\la
raflat-master\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\Users\ehab\blog\larafla
t-master\bootstrap/../vendor/autoload.php' (include_path='\xampp\php\PEAR') in C
:\Users\ehab\blog\laraflat-master\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\Users\ehab\blog\laraflat-mas
ter\bootstrap/../vendor/autoload.php' (include_path='\xampp\php\PEAR') in C:\Use
rs\ehab\blog\laraflat-master\bootstrap\autoload.php on line 17

فى الاول حاولت
 Install Form Composer
 windows 7 لكن فى مشكلة مع 
حملت الملفات  لكن بردو مش شغال

**Comment by zizohassan** [comment]
composer install 
الاول قبل ما تعمل اي حاجة 
وبعدين 
php artisan migrate
php artisan db:seed
