### ISSUE TITLE
Java script error in Admin control panel

### ISSUE THREAD

**Issue by husseinsayed** [zizohassan/laraflat#35]
I'm getting this error and i think it breaking executing script after page load like in add page i can't alternate between page title and page body in (ar and en ).
The error is:-
Uncaught Error: Invalid dimensions for plot, width = null, height = null
    at Canvas.resize (jquery.flot.js:135)
    at new Canvas (jquery.flot.js:114)
    at setupCanvases (jquery.flot.js:1313)
    at new Plot (jquery.flot.js:707)
    at Function.$.plot (jquery.flot.js:3146)
    at dashboard.js:50
    at dashboard.js:176
-----------------------------------
Canvas.resize | @ | jquery.flot.js:135
Canvas | @ | jquery.flot.js:114
setupCanvases | @ | jquery.flot.js:1313
Plot | @ | jquery.flot.js:707
$.plot | @ | jquery.flot.js:3146
(anonymous) | @ | dashboard.js:50
(anonymous) | @ | dashboard.js:176

**Comment by zizohassan** [comment]
send us screenshot to the error 
and the action you made to make this error show

**Comment by husseinsayed** [comment]
it is just after page loads
![Uploading laraflate_erro
![laraflate_error](https://user-images.githubusercontent.com/33466971/32646163-e9d9ed7e-c5f3-11e7-9cef-90c50ad9d35d.jpg)
r.png…]()

**Comment by zizohassan** [comment]
it just from design 
we will work on this 
thanks
