### ISSUE TITLE
Ajax error 

### ISSUE THREAD

**Issue by MMagde** [zizohassan/laraflat#36]
this happens whenever i try to browse most of modules ex(permissions)
![image](https://user-images.githubusercontent.com/22965555/32953995-85187fb4-cbba-11e7-8963-b3d41b5ececf.png)
Have I done something wrong?

**Comment by madrista** [comment]
Same issue when i try to make new Permission.

**Comment by MMagde** [comment]
It worked fine  :D 
thanks alot @madrista
