### ISSUE TITLE
error when using Categorie::pluck()

### ISSUE THREAD

**Issue by olfat123** [zizohassan/laraflat#37]
![category_issue](https://user-images.githubusercontent.com/33803983/32997561-6f3fa2b2-cd9a-11e7-8da2-088431d83019.png)

**Comment by zizohassan** [comment]
when that happen

**Comment by olfat123** [comment]
when click to add new product . this code responsible of retrieving the categories to add product page

**Comment by olfat123** [comment]
use App\Application\Model\Categorie;

solved , we have to add this line in productController.php 

use App\Application\Model\Categorie;
