### ISSUE TITLE
ajax problem

### ISSUE THREAD

**Issue by EslamHamed2017** [zizohassan/laraflat#38]
DataTables warning: table id=dataTableBuilder - Ajax error. For more information about this error how to fix this

**Comment by zizohassan** [comment]
in what pave you see this
give us screen shot

**Comment by EslamHamed2017** [comment]
['page',' logs', 'contact Us']
![img_20171124_092757](https://user-images.githubusercontent.com/25536323/33201340-c006bce4-d100-11e7-99e3-1097663616b2.jpg)

**Comment by zizohassan** [comment]
put your project on htdocs or www and run the project like this
localhost/websitefolder/public
it must fix this error
