### ISSUE TITLE
CRUD Controller Need to add Other functins with views

### ISSUE THREAD

**Issue by Elshaden** [zizohassan/laraflat#39]
Hi,
First I congratulate you on this marvelous work.

If I want to add another function other than CRUD in the controller with admin view,
how do I fix the permission issue , the new view and function is not related to any model
say I want to add advance search page with filters, 
I tried but all the time I get back to home page when I call the route to the new function and view.

**Comment by zizohassan** [comment]
Put the model you search in ...
and put the function name in the middleware 
laraflat/app/Http/Middleware/PermissionMiddleware.php
and assign the name of permission in this array

**Comment by Elshaden** [comment]
Like This ?

'replayEmail' =>[
                'edit'
            ],
'search'=>[
'view'
],

**Comment by zizohassan** [comment]
this mean that the function search will be under the view permission
any one have access to this model view permission 
will allow ot exeute this function
'search'=>[
'view'
],
