### ISSUE TITLE
ajax error

### ISSUE THREAD

**Issue by mahmoud1292** [zizohassan/laraflat#40]
Data tables warning: table id=dataTableBuilder - Ajax error.For mor information about this error, please see http://datatable.net/tn/7 
![untitled](https://user-images.githubusercontent.com/29343265/33334386-494f195a-d472-11e7-9c36-391b2b205ffa.png)

**Comment by zizohassan** [comment]
open the console and you will find error 
open this error and give us screenshot

**Comment by mahmoud1292** [comment]
![untitlded](https://user-images.githubusercontent.com/29343265/33340463-cf299fde-d484-11e7-909e-9b1712b023fb.png)

**Comment by a17mad** [comment]
Go to network tab and press F5 key 
it will show you the error come from

**Comment by mahmoud1292** [comment]
![untitleddd](https://user-images.githubusercontent.com/29343265/33347274-fbac59c8-d49a-11e7-9fb8-deab66d85741.png)


i can't fix this error

**Comment by a17mad** [comment]
press now on the page whitch color is red and the error details will shown
the problem with data table you must forget to add or update the value of the record
