### ISSUE TITLE
error when redirect to admin panel

### ISSUE THREAD

**Issue by AliDorgham** [zizohassan/laraflat#44]
when i login with admin ,it redirect me to 404 page
in database there is no record  in permission table and permission roles 
i hope you reply 
thank

**Comment by AliDorgham** [comment]
![capture](https://user-images.githubusercontent.com/34063592/33532309-3ec61d20-d8a1-11e7-87cd-231ec46b8559.PNG)

**Comment by AliDorgham** [comment]
i log with 
admin@gmail.com
and pass :admin

**Comment by zizohassan** [comment]
you must execute this command 
php artisan db:seed
then you must login to this url 
http://127.0.0.1:8000/en/admin/home

**Comment by OmarAlesharie** [comment]
Dear @zizohassan  I'm facing the same issue and yes I did the ( php artisan db:seed) but still facing the same problem

**Comment by zizohassan** [comment]
give me screen shot form your database

**Comment by OmarAlesharie** [comment]
Dear @zizohassan find below details:
I visit this link :   http://127.0.0.1:8000/admin/home
which redirect me to login page: http://127.0.0.1:8000/en/login
and after login it redirected me to: http://127.0.0.1:8000/505
but you can see in the last image the the admin account is logged in 

![db1](https://user-images.githubusercontent.com/30577507/33594169-dfa59006-d9a3-11e7-85e1-532e217a18da.jpg)
![db2](https://user-images.githubusercontent.com/30577507/33594170-dfc774dc-d9a3-11e7-9bf9-bbb76a69c6f8.jpg)
![login link](https://user-images.githubusercontent.com/30577507/33594172-dfebec68-d9a3-11e7-87b2-c96e6597043d.jpg)
![adminlogedin](https://user-images.githubusercontent.com/30577507/33594280-5ecfaf4c-d9a4-11e7-9809-2bdc83be5a5f.jpg)

**Comment by djoudi** [comment]
the same problem with me @zizohassan

**Comment by zizohassan** [comment]
we will check this and give you feed back

**Comment by achraffessi** [comment]
Hi,

please check the Permissions:run method in Database Seeder
this line 'getControllerByType($keyType , 'array')' give an empty array
it comes from the 'getControllersFromFolders' function

it doesn't work with windows + wamp 2.x

thank you, and keep up the good work

**Comment by zizohassan** [comment]
@achraffessi 

when you test this 
this must be worked now

**Comment by zizohassan** [comment]
we test it at windows,linux,mac 
and it works fine now 

thanks friend
