### ISSUE TITLE
new Form generator error

### ISSUE THREAD

**Issue by Elshaden** [zizohassan/laraflat#45]
HI
In the new version in generating new admin_model
when adding more than one item you get this error

Undefined offset: 0
in :…/app/Application/Controllers/Admin/CommandsController.php   line 128

 if ($request->colsName) {
            $count = 0;
            foreach ($request->colsName as $key => $cols) {
                $count++;
                $lang = $request->lang[$key] == 0 ? 'false' : 'true';
              

  **_$validation = $this->handelValidation($request->validation[$key], $request->validationVal[$key]);_**

                $colsOption .= $cols . ':' . $request->migration[$key] . ':' . $validation . ':' . $lang;
                if ($count != count($request->colsName)) {
                    $colsOption .= ',';
                }
            }
        }

**Comment by zizohassan** [comment]
can you give me the fields you add 
to test this case

**Comment by Elshaden** [comment]
Ok
I added one field Table Called Owner with multiple fields, That went OK,
I trued to add another Table named Product
fileds owner_id, and name,
and that gave error I mentioned

![laraflatnewcrud1](https://user-images.githubusercontent.com/33955172/33666273-24b947d8-daa2-11e7-8830-cb7fd2443b83.PNG)
![laraflatnewcrud2](https://user-images.githubusercontent.com/33955172/33666274-24f60df8-daa2-11e7-9f27-fa38d58944ae.PNG)

**Comment by zizohassan** [comment]
you must check the max check box 
if you put value in the text box
and we will push the fix soon

**Comment by Elshaden** [comment]
Hi
I did that but still same prb,
Maybe if I re install the laraflat system will fix, but I thought you ought to know the prb.

![laraflatnewcrud1](https://user-images.githubusercontent.com/33955172/33676946-d7545ac8-dabf-11e7-93ec-8565f24cfbcb.PNG)

![laraflatnewcrud2](https://user-images.githubusercontent.com/33955172/33676968-e9de9a14-dabf-11e7-8a3a-d558996c25c5.PNG)

**Comment by Elshaden** [comment]
![laraflatnewcrud3](https://user-images.githubusercontent.com/33955172/33684195-1f4a6f50-dad6-11e7-9b07-9feea9117881.PNG)


you can see where the error comes from,
if you take your  line 
" $validation = $this->handelValidation($request->validation[$key], $request->validationVal[$key]); "
in the loop when $key from ( $request->colsName ) = 0.

in $request->validation[$key]  does not have 0 as key as you can see from the array in the image,
it has only 1 and 5, as I have only selected validation on the second column and the last one.


Now if I checkbox any validation in all columns it will work, but if I drop validation for any column it will throw an error.

God Bless.

**Comment by zizohassan** [comment]
its must work now
just pull new project 

 thanks for help
