### ISSUE TITLE
Remove unneeded action buttons

### ISSUE THREAD

**Issue by OmarAlesharie** [zizohassan/laraflat#46]
I added a user that can't delete product, it works by throwing the user out when he tries to delete something from the products, but I don't want the user to have a delete button from the first place, should I do that by code?
or I missed something in permissions, rules, or groups?

![nodeletebutton](https://user-images.githubusercontent.com/30577507/33710165-c6fa3c1a-db50-11e7-8e02-f4bf80d5c1c1.jpg)

**Comment by a17mad** [comment]
you didn't make any thing wrong .. it's normal to throw the user out that happend because permission

 you can make if statement on datatable check if the user have access to delete show the delete button else don't show it

**Comment by zizohassan** [comment]
laraflat add permissions automatic to the user , admin groups 
when you add new model 
you can remover the button from the dom
