### ISSUE TITLE
Warning: Ajax error in Page ['page' , 'permission' , 'log', 'contact us']

### ISSUE THREAD

**Issue by EslamHamed2017** [zizohassan/laraflat#48]
DataTables warning: table id=dataTableBuilder - Ajax error. For more information about this error, please see http://datatables.net/tn/7

this error come when i open this page 
i try to solve it with 
$.fn.dataTable.ext.errMode = 'throw';
and solved 
but the page take along time to get data and some time show end first process and reload it and 
data come 

i am sorry for my error 
but i need to use laraflat thanks for u

**Comment by zizohassan** [comment]
how you run the website 
php artisan serve ??

**Comment by EslamHamed2017** [comment]
Yes and try to do make model when i do execute don't work

**Comment by zizohassan** [comment]
just put your project in htdocs or www folder
and run it the datatable have some 
problem when run from php artisan
