### ISSUE TITLE
Can i control an existing model created ordinary by php artisan make:mode and connected to table with out making migration through this admin panel ?? 

### ISSUE THREAD

**Issue by alihassan161820** [zizohassan/laraflat#5]

**Comment by a17mad** [comment]
يعنى محتاج تنشأ الموديل والموديل دا يتعامل مع جدول موجود حاليا ؟؟

**Comment by a17mad** [comment]
![screenshot-laracasts com-2017-06-14-04-02-14](https://user-images.githubusercontent.com/7467122/27112274-512394a2-50b6-11e7-9cde-ba8854369075.png)

**Comment by alihassan161820** [comment]
لا هو الموديل موجود و الجدول موجود و متربطين ينفع اتحكم بقي فيه من لوحة التحكم ان اعمل add edit delete للعناصر بتاعته

**Comment by zizohassan** [comment]
الافضل انك تعمل المديول من خلال الامر
php artisan make:admin_model ModeName
عشان فيه دوال كثيرة في الكترولر و الدتا تيبل وخلافة
بتبقي متظبته عشان تقرا من المديول اللي بيتعمل
