### ISSUE TITLE
Can't write image data to path

### ISSUE THREAD

**Issue by AliDorgham** [zizohassan/laraflat#50]
Can't write image data to path (files\38655_1512922711.png) 
when i add image column i get this line of Error  
![aaa](https://user-images.githubusercontent.com/34063592/33806871-daf7e586-ddd6-11e7-910f-ac6e0b865bc8.png)

**Comment by zizohassan** [comment]
go to public folder
make new folder call files
and inside files folder make new folder small
this will fix the problem
