### ISSUE TITLE
No labels for the new entries

### ISSUE THREAD

**Issue by OmarAlesharie** [zizohassan/laraflat#51]
No labels for the new entries in both admin and website

![no_lablels](https://user-images.githubusercontent.com/30577507/33822585-27559742-de69-11e7-82d6-bfbe009c1c1d.png)

**Comment by zizohassan** [comment]
you must go to the develop > translation > search for post
and add the translation words 
this will make the labels appear

**Comment by OmarAlesharie** [comment]
@zizohassan Thanks
