### ISSUE TITLE
Multi Language Entries

### ISSUE THREAD

**Issue by OmarAlesharie** [zizohassan/laraflat#52]
Can't switch back to English after selecting the Arabic tab, only in admin, it's working in website

![cant_switch_back_to_english](https://user-images.githubusercontent.com/30577507/33823111-fc7d4720-de6a-11e7-8287-d3d3bb746f45.png)

**Comment by zizohassan** [comment]
we fix it just
git pull origin master
and this will fix it

**Comment by OmarAlesharie** [comment]
@zizohassan Thanks
