### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mhsenpc** [zizohassan/laraflat#56]
after I migrated and ran the seeders.still this line was problemtaic

     return \App\Application\Model\Menu::where('name' , $name)->with(['item' => function($query){
        return $query->orderBy('order' , 'asc');
    }])->first()->item->groupBy('parent_id');

"Trying to get property of non-object (View: /tmp/laraflat/app/Application/views/layouts/menu.blade.php) (View: /tmp/laraflat/app/Application/views/layouts/menu. ▶"

i installed it with composer create-project --prefer-dist laraflat/laraflat

**Comment by zizohassan** [comment]
pull form the dev this will be fix
