### ISSUE TITLE
Error in Pagination 

### ISSUE THREAD

**Issue by olfat123** [zizohassan/laraflat#59]
Undefined variable: items (View: C:\xampp\htdocs\laraflat2\app\Application\views\vendor\pagination\default.blade.php)

when i put this code in the view 
<div class="text-center">{!! $posts->links(); !!}</div>

**Comment by zizohassan** [comment]
copy files from /resources/views/vendor/pagination 
copy all files on this path to this path
app/Appliction/views/vendor/pagination
this shoud fix this issues

**Comment by olfat123** [comment]
same error !!!


![image](https://user-images.githubusercontent.com/33803983/35768979-bafdb376-090c-11e8-801b-2c0e32fcfff7.png)

**Comment by zizohassan** [comment]
show us the code of app/application/view/post/index.blade.php
app/application/helpers/adminTheme.php

**Comment by olfat123** [comment]
1-code of app/application/view/post/index.blade.php

@extends('layouts.app')

@section('content')
<div class="container">
    
	<div class="panel-heading">{{ adminTrans('website','posts')}}</div>
	<div class="row form-group product-chooser">
		@foreach($posts as $post)

			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
				<div class="product-chooser-item selected" >
					<iframe width="320" height="215" class="img-rounded col-xs-4 col-sm-4 col-md-12 col-lg-12" src="https://www.youtube.com/embed/{{$post->video}}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>  
					<div class="col-xs-8 col-sm-8 col-md-12 col-lg-12">
						<span class="title"><a href="/posts/{{$post->id}}">{{ getDefaultValueKey($post->title) }}</a></span>
						<div class="clear"></div>
						<span class="description">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.</span>
						<input type="radio" name="product" value="mobile_desktop" checked="checked">
					</div>
					<div class="clear"></div>
				</div>
			</div>
						
		@endforeach

	</div>
	{{ $posts->links() }}

			
</div>
@endsection


2-code of app/application/helpers/adminTheme.php

<?php

function layoutPath($file){
    return "admin.theme.".env('THEME').".".$file;
}

function layoutMessage(){
    return layoutPath("layout.messages");
}

function layoutForm(){
    return layoutPath("layout.form");
}
function layoutExtend(){
    return layoutPath("layout.app");
}

function layoutMenu(){
    return layoutPath("layout.menu");
}

function layoutHeader(){
    return layoutPath("layout.header");
}

function layoutBreadcrumb(){
    return layoutPath("layout.breadcrumb");
}

function layoutTable(){
    return layoutPath("layout.table");
}

function dataTableConfig(){
    return [
        'dom'          => 'Bfrtip',
        'buttons'      => ['excel', 'print', 'reset', 'reload'],
        'responsive' => true,
//        'autoWidth' =>  true,
        'stateSave' => 'saveState',
        'initComplete' => "function () {
                            var allColumns = this.api().column().columns()[0].length -4 ;
                            var width = 50;
                            this.api().columns().every(function (index) {
                                var column = this;
                                if(index  <=  allColumns){
                                if(index != 0){
                                    width=100;
                                }
                                    var title = $('#dataTableBuilder thead th').eq(index).text()
                                    var input = '<input type=\"text\" class=\"form-control\" style=\"width: '+width+'px;\" placeholder=\"'+title+'\" />';
                                    $(input).appendTo($(column.footer()).empty())
                                    .on('change', function () {
                                        column.search($(this).val(), false, false, true).draw();
                                    });
                                }
                            });
                }"
    ];
}

**Comment by zizohassan** [comment]
try the new version all this fixed
