### ISSUE TITLE
Add query to datatables

### ISSUE THREAD

**Issue by sfsfco** [zizohassan/laraflat#6]
i created a new module using laraflat called (Website)
i wanted to show only the data with id=1 in datatables like this

public function index(WebsitesDataTable $dataTable){
      $this->model->where('id','1');

        return $dataTable->render('admin.website.index');
    }
but not working ... how can i deal with the datatables and send a query to it with EX please

**Comment by zizohassan** [comment]
go to this path 
app/Application/Datatables/WebsitesDataTable
find function query
change to Website::find(1)
and you get only the id 1

**Comment by sfsfco** [comment]
thanks :+1:
