### ISSUE TITLE
I cant edit admin menu

### ISSUE THREAD

**Issue by wanteed-lh** [zizohassan/laraflat#63]
![capture d ecran 2018-01-25 a 8 40 37 am](https://user-images.githubusercontent.com/23126455/35378713-ab32b5bc-01ab-11e8-9451-8b9d15e82c3d.png)

**Comment by zizohassan** [comment]
follow this topic 
https://5dmat-web.com/ar/video/939
will fix this issues

**Comment by wanteed-lh** [comment]
Thanks,  that was helper
