### ISSUE TITLE
How i can upload multi Images and upload pdf 

### ISSUE THREAD

**Issue by wanteed-lh** [zizohassan/laraflat#71]

**Comment by zizohassan** [comment]
see this video pull form dev

https://www.youtube.com/watch?v=T5X2-F9hBZk&index=15&list=PLYp_Kd32XvcrdYfidiS1_vnHtUMa96VI2

**Comment by wanteed-lh** [comment]
![capture d ecran 2018-02-05 a 8 41 13 am](https://user-images.githubusercontent.com/23126455/35795220-65e937d0-0a50-11e8-9ded-9fe25553d692.png)

**Comment by zizohassan** [comment]
give me screen shot of from you build to check some thing
