### ISSUE TITLE
 Table 'laraflat.post' doesn't exist 

### ISSUE THREAD

**Issue by badrshs** [zizohassan/laraflat#89]
I have used Laraflat Commands to create post section with 

title ( required )
body( required )
image (required  and as an image )

then from translate i finished all translation steps ,

now if i click on post then Datatable will alert an error and the error is what is showing in the image 

[here](https://i.imgur.com/AVQ777T.png)

```
"Illuminate\Database\QueryException"
file
:
"/var/www/xxxxxxxxxx/laraflat/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
line
:
664
message
:
"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laraflat.post' doesn't exist (SQL: select count(*) as aggregate from (select '1' as `row_count` from `post`) count_row_table)"
```

**Comment by wanteed-lh** [comment]
https://5dmat-web.com/ar/video/939

**Comment by badrshs** [comment]
???? this is not related to the problem at all 😆

**Comment by zizohassan** [comment]
check if you have database call laraflat and in this database have table call post

**Comment by badrshs** [comment]
I solved the problem .

as I told you in another issue (permission ) 
you have to give permission to database folder but in fact you have to give the permission to all the folder inside database like migration 

what happen is you use file_put_contents and there is no permission for this and there is no migration file => and then no new table in database . 
the thing is, I didnt get any  permission error . 

after given the right permission to migration folder the problem is solved.

**Comment by zizohassan** [comment]
good luck
