### ISSUE TITLE
SQLSTATE[HY000]: General error: PDO::ATTR_STATEMENT_CLASS requires format array(classname, array(ctor_args)); the classname must be a string specifying an existing class (SQL: select * from `post` limit 3)

### ISSUE THREAD

**Issue by wanteed-lh** [zizohassan/laraflat#90]
its work on local host but when i deploy my website on shared host i get that error 
![capture d ecran 2018-03-05 a 10 13 18 am](https://user-images.githubusercontent.com/23126455/36969597-e26c5fa8-205d-11e8-924c-b3a4c240e82f.png)

**Comment by zizohassan** [comment]
get the next version 3.0.0  then told me what happen

**Comment by wanteed-lh** [comment]
its work thanks 👍
