### ISSUE TITLE
error in php artisan db:seed

### ISSUE THREAD

**Issue by AdelShokry** [zizohassan/laraflat#94]
Seeding: AdminGroup

In Carbon.php line 9:

Declaration of Illuminate\Support\Carbon::__set_state($array) should be com
patible with Carbon\Carbon::__set_state(array $state)

**Comment by zizohassan** [comment]
What your operating system

**Comment by zizohassan** [comment]
open this path 
vendor/laravel/framework/composer.json

go to line 26
change this line 
`  "nesbot/carbon": "~1.20", `
with 
`  "nesbot/carbon": "~1.24.1", `

then composer update

and enjoy

**Comment by AdelShokry** [comment]
mac

**Comment by zizohassan** [comment]
done
