### ISSUE TITLE
php artisan db:seed

### ISSUE THREAD

**Issue by THEBRAINCOCH** [zizohassan/laraflat#95]
In Carbon.php line 9:

  Declaration of Illuminate\Support\Carbon::__set_state($array) should be compatible with Carbon\Carbon::__set_state(array $state)

ErrorException (E_WARNING)
Declaration of Illuminate\Support\Carbon::__set_state($array) should be compatible with Carbon\Carbon::__set_state(array $state)
Seeding: AdminGroup

**Comment by zizohassan** [comment]
What your operating system
